version: '3'

x-scanner:
  &scanner
  build:
    context: .
    dockerfile: Dockerfile
  networks:
    - bs_default
    - tp_default
    - bs_redis_db
    - mongo_db
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "5M"
      max-file: "5"

x-db:
  &db
  REDIS_URL: redis://redis:6379
  REDIS_PORT: 6379
  REDIS_HOST: redis
  MONGO_URL: mongodb://piperFinance:Piper2022@mongo:27017
  TP_SERVER: http://tp:9765

services:
  bs_main:
    <<: *scanner
    ports:
      - 7001:7001
      - 6001:6001
    environment:
      ASYNQ_MON_URL: ":7001"
      API_URL: ":6001"
      MONGO_DBNAME: BS_T1
      REDIS_DB: 4
      MAX_CONCURRENT_WORKER: 60
      SUPPORTED_CHAINS: "1,250,56,137,43114"
      # SUPPORTED_CHAINS: "1,250,56,137,43114,12306,42161,100,2021,40,9001,1284,10,58,121"
      <<: *db

  bs_redis:
    image: redis:latest
    hostname: redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PORT_NUMBER=6379
      - REDIS_AOF_ENABLED=no
    expose:
      - 6379
    restart: always
    command: redis-server --appendonly yes
    networks:
      - bs_redis_db
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - ./data/redis:/data

networks:
  tp_default:
    external:
      name: tp_default
  bs_redis_db:
    name: redis_db
  mongo_db:
    external:
      name: mongo_db
  bs_default:
    driver: bridge
    name: bs_default
